<<<<<<< HEAD
# Generated by Django 5.2.8 on 2025-11-20 10:53
=======
# Generated by Django 5.2.8 on 2025-11-20 08:33
>>>>>>> ee72244c6532dfb87ea48ded4361adfd1176a23f

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='tokens',
        ),
        migrations.CreateModel(
            name='TokenTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_token', models.IntegerField(default=0)),
                ('output_token', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_transactions', to='Auth.customuser')),
            ],
        ),
    ]
